notv2016/notv2016/urls.py
from django.conf.urls import url, include, patterns
from django.contrib import admin
from django.conf import settings
from django.views.static import serve

from django.contrib.auth.views import login, logout, password_reset, password_reset_done, \
    password_reset_confirm, password_reset_complete
from users.views import register_user, account, index, password_change, NOTVUserUpdate


urlpatterns = patterns(
    '',
    url(r'^notv/', include(patterns(
        '',

        url(r'^login/$', login, {"template_name": "login.html"}),
        url(r'^logout/$', logout, {"next_page": "/notv/account"}),
        url(r'^register/$', register_user),
        url(r'^events/$', index),
        url(r'^account/$', account),
        url(r'^account/update/$', NOTVUserUpdate.as_view(template_name='notvuser_form.html', success_url="/account/")),
        url(r'^password/change/$', password_change,
            {"post_change_redirect": "notv/user/password/done"}),
        url(r'^user/password/reset/$', password_reset,
            {'post_reset_redirect': '/notv/user/password/reset/done/',
                'email_template_name': 'password_reset_email.html',
                "template_name": "password_reset_form.html"}, name="password_reset"),
        url(r'^user/password/reset/done/$', password_reset_done,
            {"template_name": "password_reset_done.html",
                "post_change_redirect": "notv/user/password/done"},
            ),
        url(r'^reset/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', password_reset_confirm, {'template_name': 'password_change_form.html',  'post_reset_redirect': '/notv/logout/'}),
        url(r'^user/password/done/$', password_reset_complete,
            {"template_name": "password_reset_complete.html"}),
        url(r'^static/(?P<path>.*)$', serve,
            {'document_root': settings.STATIC_ROOT}
            ),
    ),
    )))

urlpatterns += patterns(
    '',
    url(r'^notv/admin/', admin.site.urls),
    )

notv2016/users/models.py
from django.db import models
from django.contrib.auth.models import BaseUserManager, AbstractBaseUser, Group


class UserManager(BaseUserManager):
    def create_user(self, email, password=None):
        if not email:
            raise ValueError('Необходимо ввести электронный адрес')

        user = self.model(
            email=UserManager.normalize_email(email),
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password):
        user = self.create_user(password=password,
                                email=email)
        user.is_admin = True
        user.save(using=self._db)
        return user


class NOTVUser(AbstractBaseUser):
    """
    Пользователь
    """

    email = models.EmailField(
        verbose_name='Электронная почта',
        max_length=32,
        unique=True,
        db_index=True,
    )

    avatar = models.ImageField(
        verbose_name='Аватар',
        upload_to='images/%Y/%m',
        blank=True,
    )

    first_name = models.CharField(
        verbose_name='Имя',
        max_length=1024,
        blank=True,
    )

    last_name = models.CharField(
        verbose_name='Фамилия',
        max_length=1024,
        blank=True,
    )

    department = models.CharField(
        verbose_name='Организация',
        max_length=1024,
        blank=True,
    )

    position = models.CharField(
        verbose_name='Должность',
        max_length=255,
        blank=True,
    )

    tel = models.CharField(
        verbose_name='Телефон',
        max_length=255,
        blank=True,
    )

    is_admin = models.BooleanField(
        verbose_name='Является администратором?',
        default=False,
    )

    is_superuser = models.BooleanField(
        verbose_name='Является суперпользователем?',
        default=False,
    )

    is_active = models.BooleanField(
        verbose_name='Активный',
        default=True,
    )

    is_paid = models.BooleanField(
        verbose_name='Оплатил',
        default=False,
    )

    online = 'online'
    offline = 'offline'
    STATUS = (
        (online, 'Заочно'),
        (offline, 'Очно')
    )

    status = models.CharField("Статус", max_length=7, choices=STATUS, default=offline)

    date = models.DateField(auto_now_add=True, blank=True)

    groups = models.ManyToManyField(Group)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = UserManager()

    def get_full_name(self):
        return '%s %s' % (self.last_name,
                          self.first_name,)

    def __str__(self):
        return self.email

    def get_short_name(self):
        return self.email

    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, app_label):
        return True

    @property
    def is_staff(self):
        return self.is_admin

    @property
    def is_root(self):
        return self.is_superuser


class Meta:
    verbose_name = ('Пользователь')
    verbose_name_plural = ('Пользователи')

notv2016/users/forms.py
from django import forms
from .models import NOTVUser
from django.contrib.auth.forms import ReadOnlyPasswordHashField


class UserCreationForm(forms.ModelForm):
    password1 = forms.CharField(label='Пароль', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Подтверждение пароля', widget=forms.PasswordInput)

    class Meta:
        model = NOTVUser
        fields = ('email', 'password')

    def clean_password2(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError('Введённые пароли не совпадают.')
        return password2

    def save(self, commit=True):
        user = super(UserCreationForm, self).save(commit=False)
        user.set_password(self.cleaned_data['password1'])
        if commit:
            user.save()
        return user


class UserChangeForm(forms.ModelForm):
    password = ReadOnlyPasswordHashField()

    class Meta:
        model = NOTVUser
        fields = '__all__'


class RegistrationForm(UserCreationForm):

    class Meta:
        model = NOTVUser
        fields = '__all__'
        exclude = ['password', 'last_login', 'avatar', 'is_admin', 'is_superuser', 'is_paid', 'groups']

    def clean_password2(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError('Введённые пароли не совпадают.')
        return password2

    def save(self, commit=True):
        user = super(RegistrationForm, self).save(commit=False)
        user.set_password(self.cleaned_data['password1'])
        if commit:
            user.save()
        return user

notv2016/users/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.template.context_processors import csrf
from django.contrib.auth import authenticate, login, update_session_auth_hash
from django.shortcuts import resolve_url, get_object_or_404
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.decorators import login_required
from django.template.response import TemplateResponse
from django.views.decorators.csrf import csrf_protect
from django.views.generic.edit import UpdateView
from django.utils.translation import ugettext as _

from .forms import RegistrationForm

from .models import NOTVUser

import logging


logger = logging.getLogger(__name__)


@csrf_protect
def register_user(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            new_user = authenticate(email=request.POST['email'],
                                    password=request.POST['password1'])
            login(request, new_user)
            return HttpResponseRedirect('/notv/account/')
        else:
            logger.info('Invalid form')
    else:
        form = RegistrationForm()
    args = {}
    args.update(csrf(request))
    args['form'] = RegistrationForm()
    return render(request, 'register.html', args)


def index(request):
    context = {}
    context['user'] = request.user
    return render(request, 'index.html', context)



def account(request):
    user = request.user

    context = {'user': user}
    context['user'] = request.user
    return render(request, 'account.html', context)


@csrf_protect
def password_change(request,
                    template_name='password_change_form.html',
                    post_change_redirect=None,
                    password_change_form=PasswordChangeForm,
                    extra_context=None):

    post_change_redirect = resolve_url('/user/password/done/')
    if request.method == "POST":
        form = password_change_form(user=request.user, data=request.POST)
        if form.is_valid():
            form.save()
            # Updating the password logs out all other sessions for the user
            # except the current one.
            update_session_auth_hash(request, form.user)
            return HttpResponseRedirect(post_change_redirect)
    else:
        form = password_change_form(user=request.user)
    context = {
        'form': form,
        'title': _('Password change'),
    }
    if extra_context is not None:
        context.update(extra_context)

    return TemplateResponse(request, template_name, context)


class NOTVUserUpdate(UpdateView):
    model = NOTVUser
    fields = ['avatar', 'first_name', 'last_name', 'department', 'position', 'tel', 'status']

    def get_object(self):
        return get_object_or_404(NOTVUser, pk=self.request.session['_auth_user_id'])

    def get_success_url(self):
        return '/notv/account'

    def get_context_data(self, **kwargs):

        context = super(NOTVUserUpdate, self).get_context_data(**kwargs)
        context['user'] = get_object_or_404(NOTVUser, pk=self.request.session['_auth_user_id'])

        return context

notv2016/templates/users/account.html
{% extends "base.html" %}
{% load i18n %}
{% block content %}

<div class="for-footer">
    <div class="main-title">
        <h1><span class="in"><span>{% trans 'Личный кабинет' %}</span></span></h1>
    </div>
    <div class="section breadcrumbs">
        <div class="row">
            <div class="col3">
                <span class="breadcrumbs-item">
                    <a href="http://notv.urfu.ru/ru">{% trans 'Главная страница' %}</a>
                </span>
                <span class="divide">/</span>
                <span class="breadcrumbs-item">
                    <a href="" class="no-underline"><span>{% trans 'Личный кабинет' %}</span></a>
                </span>
            </div>
        </div>
    </div>
    <div class="section content">
        <div class="row">
            <div class="col2 lea_alex">
                <header>
                    <h1 class="title">
                      <span class="title-super">{% trans 'Личный кабинет' %}</span>
                    </h1>
                  </header>
            {% if request.user.is_authenticated %}
                <p>{% trans "Добро пожаловать, " %}{{ request.user.first_name }} {{ request.user.last_name }}</p>
            {{ form.as_p }}
                <p>Вы можете изменить свои данные, перейдя по <a href="../account/update/"> ссылке</a>.
                <p>Вы можете изменить свой пароль, перейдя по <a href="../password/change/"> ссылке</a>.

                <p style="padding-top:1em;color:red;">Программа конференции и выбор индивидуальной траектории посещения мероприятий будут доступны 05.04.2016 г.</p>
                {# <p>{% trans 'Страница с событиями конференции доступна по <a href="../events/">ссылке.</a>' %} #}
            {% else %}
                <p>Вы не зарегистрированы. <br />
                    Пожалуйста, <a href="/notv/register">зарегистрируйтесь</a> или <a href="/notv/login">войдите в систему</a>.</p>
            {%endif%}

    </div>
    <div class="col">
        <aside role="complementary">
            <style>
            .smaller {
              font-size:80%;
            }
            .gray {
              color: #333;
            }

            .smaller-header {
              font-size: 20px;
            }
            .justify {
              text-align: justify;
              text-indent: 20px;
            }
            </style>
        <div class="smaller">
            <header>
                <h3 class="sr gray">{% trans 'Помощь в входе' %}</h3>
            </header>
            <div class="cta cta-welcome">
                <h3 class="gray smaller-header"></h3>
                <p class="justify">
                     {% trans 'Укажите свои данные, которые были использованные при регистрации. Если вы не можете вспомнить свой пароль, то для его востановления перейдите по данной <a href="/notv/user/password/reset/">ссылке.' %}</a>
                </p>
            </div>




</div>

  </aside>

    </div>
  </div>
</div> <!-- /for-footer -->
</div>
{% endblock %}

notv2016/templates/users/logged_out.html
{% extends "base.html" %}
{% load i18n %}

{% block breadcrumbs %}<div class="breadcrumbs"><a href="{% url 'admin:index' %}">{% trans 'Home' %}</a></div>{% endblock %}

{% block content %}

<p>{% trans "Thanks for spending some quality time with the Web site today." %}</p>

<p><a href="{% url 'admin:index' %}">{% trans 'Log in again' %}</a></p>

{% endblock %}

notv2016/templates/users/notvuser_form.html
{% extends "base.html" %}
{% load i18n %}
{% block content %}
<div class="for-footer">
    <div class="main-title">
        <h1><span class="in"><span>{% trans 'Изменение учетных данных' %}</span></span></h1>
    </div>
    <div class="section breadcrumbs">
        <div class="row">
            <div class="col3">
                <span class="breadcrumbs-item">
                    <a href="http://notv.urfu.ru/ru">{% trans 'Главная страница' %}</a>
                </span>
                <span class="divide">/</span>
                <span class="breadcrumbs-item">
                    <a href="../account/">{% trans 'Личный кабинет' %}</a>
                </span>
                <span class="divide">/</span>
                <span class="breadcrumbs-item">
                    <a href="" class="no-underline"><span>{% trans 'Изменение учетных данных' %}</span></a>
                </span>
            </div>
        </div>
    </div>
    <div class="section content">
        <div class="row">
            <div class="col2 lea_alex">
                <header>
                    <h1 class="title">
                      <span class="title-super">{% trans 'Изменение учетных данных' %}</span>
                    </h1>
                  </header>

<!-- начало формы  -->

        <div class="ui fluid error form segment">

        {% if form.non_field_errors %}
        {% for error in form.non_field_errors %}
        <div class="ui error message">
            <div class="header">Ошибка!</div>
            <p>{% trans 'Введите корректные электронную почту и пароль.' %}</p>
        </div>
        {% endfor %}
        {% endif %}

        {% if form.errors and not form.non_field_errors %}
        <div class="ui error message">
            <div class="header">Error!</div>
            <p>{% trans 'Что-то пошло не так...' %}</p>
        </div>
        {% endif %}

        </div>

<form action="" method="post">
    {% csrf_token %}
    <!--<div class="cont-input"><label for="id_avatar">Аватар:</label> <input id="id_avatar" name="avatar" type="file"></div>-->
<div class="cont-input"><label for="id_first_name">Имя:</label> <input id="id_first_name" maxlength="1024" name="first_name" type="text" value="{{ user.first_name }}"></div>
<div class="cont-input"><label for="id_last_name">Фамилия:</label> <input id="id_last_name" maxlength="1024" name="last_name" type="text" value="{{ user.last_name }}"></div>
<div class="cont-input"><label for="id_department">Университет/Подразделение:</label> <input id="id_department" maxlength="1024" name="department" type="text" value="{{ user.department }}"></div>
<div class="cont-input"><label for="id_position">Должность:</label> <input id="id_position" maxlength="255" name="position" type="text" value="{{ user.position }}"></div>
<div class="cont-input"><label for="id_tel">Телефон:</label> <input id="id_tel" maxlength="255" name="tel" type="text" value="{{ user.tel }}"></div>
<div class="cont-input"><label for="id_status">Статус:</label> <select id="id_status" name="status">
<option value="online"
    {% if user.status == 'online' %}
        selected="selected"
    {% endif %}
    >Заочно</option>
<option value="offline"
    {% if user.status == 'offline' %}
        selected="selected"
    {% endif %}
        >Очно</option>
</select></div>

            <div class="cont-input cont-btn">
                <input class="button_create" type="submit" value="{% trans 'Сохранить' %}"/>
            </div>
        </form>
    </div>
<!-- конец формы-->

    </div>
    <div class="col">
        <aside role="complementary">
            <style>
            .smaller {
              font-size:80%;
            }
            .gray {
              color: #333;
            }

            .smaller-header {
              font-size: 20px;
            }
            .justify {
              text-align: justify;
              text-indent: 20px;
            }
            .cont-input label {
                width: 250px !important;
                }
            </style>
  </aside>

    </div>
  </div>
</div> <!-- /for-footer -->
</div>
{% endblock %}

notv2016/templates/users/password_change_done.html
{% extends "base.html" %}
{% load i18n %}
{% block userlinks %}{% url 'django-admindocs-docroot' as docsroot %}{% if docsroot %}<a href="{{ docsroot }}">{% trans 'Documentation' %}</a> / {% endif %}{% trans 'Change password' %} / <a href="{% url 'admin:logout' %}">{% trans 'Log out' %}</a>{% endblock %}
{% block breadcrumbs %}
<div class="breadcrumbs">
<a href="{% url 'admin:index' %}">{% trans 'Home' %}</a>
&rsaquo; {% trans 'Password change' %}
</div>
{% endblock %}

{% block title %}{{ title }}{% endblock %}
{% block content_title %}<h1>{{ title }}</h1>{% endblock %}
{% block content %}
<p>{% trans 'Your password was changed.' %}</p>
{% endblock %}

notv2016/templates/users/password_reset_complete.html
{% extends "base.html" %}
{% load i18n %}

{% block breadcrumbs %}
<div class="breadcrumbs">
<a href="{% url 'admin:index' %}">{% trans 'Home' %}</a>
&rsaquo; {% trans 'Password reset' %}
</div>
{% endblock %}

{% block title %}{{ title }}{% endblock %}
{% block content_title %}<h1>{{ title }}</h1>{% endblock %}

{% block content %}

<p>{% trans "Your password has been set.  You may go ahead and log in now." %}</p>

<p><a href="{{ login_url }}">{% trans 'Log in' %}</a></p>

{% endblock %}

notv2016/templates/users/password_reset_done.html
{% extends "base.html" %}
{% load i18n %}

{% block breadcrumbs %}
<div class="breadcrumbs">
<a href="{% url 'admin:index' %}">{% trans 'Home' %}</a>
&rsaquo; {% trans 'Password reset' %}
</div>
{% endblock %}

{% block title %}{{ title }}{% endblock %}
{% block content_title %}<h1>{{ title }}</h1>{% endblock %}
{% block content %}

<p>{% trans "We've emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly." %}</p>

<p>{% trans "If you don't receive an email, please make sure you've entered the address you registered with, and check your spam folder." %}</p>

{% endblock %}

notv2016/templates/users/password_reset_form.html
{% extends "base.html" %}
{% load i18n %}

{% block breadcrumbs %}
<div class="breadcrumbs">
<a href="{% url 'admin:index' %}">{% trans 'Home' %}</a>
&rsaquo; {% trans 'Password reset' %}
</div>
{% endblock %}

{% block title %}{{ title }}{% endblock %}
{% block content_title %}<h1>{{ title }}</h1>{% endblock %}
{% block content %}

<p>{% trans "Forgotten your password? Enter your email address below, and we'll email instructions for setting a new one." %}</p>

<form method="post">{% csrf_token %}
{{ form.email.errors }}
<p><label for="id_email">{% trans 'Email address:' %}</label> {{ form.email }} <input type="submit" value="{% trans 'Reset my password' %}" /></p>
</form>

{% endblock %}

notv2016/templates/users/register.html
{% extends "base.html" %}
{% load i18n %}
{% block content %}
<div class="for-footer">
    <div class="main-title">
        <h1><span class="in"><span>Регистрация</span></span></h1>
    </div>
    <div class="section breadcrumbs">
        <div class="row">
            <div class="col3">
                <span class="breadcrumbs-item">
                    <a href="http://notv.urfu.ru/ru">Главная страница</a>
                </span>
                <span class="divide">/</span>
                <span class="breadcrumbs-item">
                    <a href="" class="no-underline"><span>Регистрация</span></a>
                </span>
            </div>
        </div>
    </div>

<div class="section content">
   <div class="row">

      <div class="col2 lea_alex">
                  <header>
                    <h1 class="title">
                      <span class="title-super">Добро пожаловать!</span>
                    </h1>
                  </header>
            
   

            {% if form.non_field_errors %}
        {% for error in form.non_field_errors %}
        <div class="ui error message">
            <div class="header">Ошибка!</div>
            <p>Введите корректные электронную почту и пароль.</p>
        </div>
        {% endfor %}
        {% endif %}

        {% if form.errors and not form.non_field_errors %}
        <div class="ui error message">
            <div class="header">Ошибка!</div>
            <p>Что-то пошло не так...</p>
        </div>
        {% endif %}

        <form method="post" action="{% url 'users.views.register_user' %}">
            {% csrf_token %}

             <div class="cont-input">
                 <label>{{form.email.label_tag}}</label>
                 {{form.email}}
             </div>
             <div class="cont-input">
                 <label for="id_first_name">{{form.first_name.label_tag}}</label>
                 {{form.first_name}}

             </div>
             <div class="cont-input">
                 <label for="id_last_name">{{form.last_name.label_tag}}</label>
                 {{form.last_name}}
             </div>
            <div class="cont-input">
            <label for="id_department">{{form.department.label_tag}}</label>
                 {{form.department}}
            </div>
             <div class="cont-input">
             <label for="id_position">{{form.position.label_tag}}</label>
                 {{form.position}}
             </div>
             <div class="cont-input">
             <label for="id_tel">{{form.tel.label_tag}}</label>
                 {{form.tel}}
             </div>
             <div class="cont-input">
             <label for="id_status">{{form.status.label_tag}}</label>
           {{form.status}}
           </div>
             <div class="cont-input">
             <label for="id_password1">{{form.password1.label_tag}}</label>
                 {{form.password1}}
             </div>
             <div class="cont-input">
             <label for="id_password2">{{form.password2.label_tag}}</label>
                 {{form.password2}}
             </div>
             <div class="cont-input cont-btn">
            <input class="button_create" value="Зарегистрироваться" type="submit" />
            <input type="hidden" name="next" value="/notv/account/" />
            </div>
        </form>


            </div>
                <div class="col">
                                      <aside role="complementary">



    


<style>
.smaller {
  font-size:80%;
}
.gray {
  color: #333;
}

.smaller-header {
  font-size: 20px;
}
.justify {
  text-align: justify;
  text-indent: 20px;
}
</style>


<div class="smaller">

<header>
  <h3 class="sr gray">Помощь в регистрации</h3>
</header>
  <div class="cta cta-welcome">
    <h3 class="gray smaller-header">Инструкция</h3>
    <p class="justify">
        {% trans "Заполните все поля формы для регистрации. После нажатия кнопки &laquo;Зарегистрироваться&raquo; вам будет открыт доступ в личный кабинет, где вам будет доступна программа конференции в формате выбора траектории посещения мероприятий." %}
    </p>
  </div>

  <div class="cta cta-help">
    <h3 class="gray smaller-header">Нужна помощь?</h3>
    <p class="justify">Нужна помощь в регистрации? Вы можете написать нам на <a href="mailto:notv@urfu.ru?subject=Нужна помощь в регистрации">электронную почту</a>.</p>
    <p>Tакже вы можете нам позвонить по  номеру телефона: 8 (343) 374-58-24</p>
  </div>

</div>

  </aside>
                                  
    </div>
  </div>
</div> <!-- /for-footer -->
</div>



    






{% endblock %}

notv2016/templates/users/register1.html
{% extends "base.html" %}

{% block content %}
<div class="for-footer">
    <div class="main-title">
        <h1><span class="in"><span>Регистрация</span></span></h1>
    </div>
    <div class="section breadcrumbs">
        <div class="row">
            <div class="col3">
                <span class="breadcrumbs-item">
                    <a href="http://notv.urfu.ru/ru">Главная страница</a>
                </span>
                <span class="divide">/</span>
                <span class="breadcrumbs-item">
                    <a href="" class="no-underline"><span>Регистрация</span></a>
                </span>
            </div>
        </div>
    </div>

<div class="section content">
   <div class="row">

      <div class="col2 lea_alex">
                  <header>
                    <h1 class="title">
                      <span class="title-super">Добро пожаловать!</span>
                    </h1>
                  </header>
            
   
    <form action="" method="post">

        <input type="hidden" name="csrfmiddlewaretoken" value="J5fbaEHw6yGZyjMXMuDUW58N4P5X1C1Z">

        <div class="cont-input">
        <label for="id_f">Фамилия:</label>
        <input id="id_f" maxlength="1024" name="f" type="text">
        </div>

        <div class="cont-input">
        <label for="id_i">Имя:</label> 
        <input id="id_i" maxlength="1024" name="i" type="text">
        </div>

        <div class="cont-input">
        <label for="id_o">Отчество:</label>
        <input id="id_o" maxlength="1024" name="o" type="text">
        </div>

        <div class="cont-input">
        <label for="id_org">Организация:</label>
        <input id="id_org" maxlength="1024" name="org" type="text">
        </div>

        <div class="cont-input">
        <label for="id_job">Должность:</label>
        <input id="id_job" maxlength="1024" name="job" type="text">
        </div>

        <div class="cont-input">
        <label for="id_city">Город:</label>
        <input id="id_city" maxlength="1024" name="city" type="text">
        </div>

        <div class="cont-input">
        <label for="id_email">Электронная почта:</label>
        <input id="id_email" maxlength="1024" name="email" type="email">
        </div>

        <div class="cont-input">
        <label for="id_tel">Телефон:</label>
        <input id="id_tel" maxlength="1024" name="tel" type="text">
        </div>

        <div class="cont-input">
        <label for="id_status">Присутствие:</label>
        <select id="id_status" name="status">
            <option value="online">Заочно</option>
            <option value="offline" selected="selected">Очно</option>
        </select>
        </div>


        <div class="cont-input cont-btn">
            <input name="submit" id="submit" class="button_create" value="Зарегистрироваться" type="submit">
        </div>
        

    </form>


            </div>
                <div class="col">
                                      <aside role="complementary">



    


<style>
.smaller {
  font-size:80%;
}
.gray {
  color: #333;
}

.smaller-header {
  font-size: 20px;
}
.justify {
  text-align: justify;
  text-indent: 20px;
}
</style>


<div class="smaller">

<header>
  <h3 class="sr gray">Помощь в регистрации</h3>
</header>
  <div class="cta cta-welcome">
    <h3 class="gray smaller-header">Шаг первый</h3>
    <p class="justify">
      Заполните все поля формы для регистрации. После нажатия кнопки «Зарегистрироваться» вы перейдете на страницу формирования траектории посещения мероприятий конференции, а на вашу электронную почту будет отправлена персональная ссылка на вашу траекторию.
    </p>
  </div>


<div class="cta cta-nextsteps">
  <h3 class="gray smaller-header">Шаг второй</h3>
    <p class="justify">

      Перейдя по вашей персональной ссылке вы сможете изменить вашу траекторию посещения мероприятий конференции, а также прикрепить или удалить документы для публикации в электронном сборнике.
    </p>

</div>


  <div class="cta cta-help">
    <h3 class="gray smaller-header">Нужна помощь?</h3>
    <p class="justify">Нужна помощь в регистрации? Вы можете написать нам на <a href="mailto:notv@urfu.ru?subject=Нужна помощь в регистрации">электронную почту</a>.</p>
    <p>Tакже вы можете нам позвонить по  номеру телефона: 8 (343) 374-58-24</p>
  </div>

</div>

  </aside>
                                  
    </div>
  </div>
</div> <!-- /for-footer -->
</div>


<div class="container">
    <h1 class="ui teal medium header">Регистрация в NOTV2016:</h1>
    <div class="ui fluid error form segment">

        {% if form.non_field_errors %}
        {% for error in form.non_field_errors %}
        <div class="ui error message">
            <div class="header">Ошибка!</div>
            <p>Введите корректные электронную почту и пароль.</p>
        </div>
        {% endfor %}
        {% endif %}

        {% if form.errors and not form.non_field_errors %}
        <div class="ui error message">
            <div class="header">Ошибка!</div>
            <p>Что-то пошло не так...</p>
        </div>
        {% endif %}

        <form method="post" action="register/">
            {% csrf_token %}

            <div class="ui teal segment">
                <div class="required field">
                    <label>{{ form.email.label_tag }}</label>
                    {{ form.email }}
                </div>
            </div>

            <div class="ui teal segment">
                <div class="two fields">
                    <div class="field">
                        <label>{{ form.first_name.label_tag }}</label>
                        {{ form.first_name }}
                    </div>

                    <div class="field">
                        <label>{{ form.last_name.label_tag }}</label>
                        {{ form.last_name }}
                    </div>
                </div>
            </div>

            <div class="ui teal segment">
                <div class="field">
                    <label>{{ form.department.label_tag }}</label>
                    {{ form.department }}
                </div>
            </div>

            <div class="ui teal segment">
                <div class="required field">
                    <label>{{ form.password1.label_tag }}</label>
                    {{ form.password1 }}
                </div>
                <div class="required field">
                    <label>{{ form.password2.label_tag }}</label>
                    {{ form.password2 }}
                </div>
            </div>

            <input class="ui teal submit button" type="submit" value="Register"/>
            <input type="hidden" name="next" value="/" />
        </form>
    </div>
</div>

{% endblock %}